# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
orbs:
  node: circleci/node@4.7.0
  salesforce-sfdx: circleci/salesforce-sfdx@2.2.0
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install:
          install-yarn: true 
          lts: true
      - run: node --version 
      - salesforce-sfdx/install:
          version: latest
      
      - run:
            name: get SFDX version
            command: sfdx -v 

workflows:
  example-workflow:
    jobs:
      - example-job