# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
orbs:
  node: circleci/node@4.7.0
  salesforce-sfdx: circleci/salesforce-sfdx@2.2.0
jobs:
  example-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - node/install:
          install-yarn: true 
          lts: true
      - run: node --version 
      - run:
          name: extract keys
          command: $SFDC_SERVER_KEY | base64 -d > keys/server.key
          
      - salesforce-sfdx/install:
          version: latest
      
      - run:
          name: Login to Production
          command: echo "Setting up Production Connection..."
      
      - run:
          name: create keys
          command: mkdir keys

      
          
      - run:
          name: "Authenticating..."
          command: sfdx force:auth:jwt:grant --clientid $SFDC_PROD_CLIENTID --jwtkeyfile keys/server.key --username $SFDC_PROD_USER --setdefaultdevhubusername -a DevHub

      - run:
          name: "showing org list..."
          command: sfdx force:org:list

workflows:
  example-workflow:
    jobs:
      - example-job